# Generated by Django 3.1.2 on 2022-03-14 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='course name')),
                ('course_link', models.URLField(unique=True, verbose_name='course link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('course', models.ManyToManyField(related_name='users', to='bootcamp.Course')),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.IntegerField(blank=True, null=True, verbose_name='question_1')),
                ('question_2', models.IntegerField(blank=True, null=True, verbose_name='question_2')),
                ('question_3', models.IntegerField(blank=True, null=True, verbose_name='question_3')),
                ('question_4', models.IntegerField(blank=True, null=True, verbose_name='question_4')),
                ('question_5', models.IntegerField(blank=True, null=True, verbose_name='question_5')),
                ('question_6', models.IntegerField(blank=True, null=True, verbose_name='question_6')),
                ('question_7', models.IntegerField(blank=True, null=True, verbose_name='question_7')),
                ('question_8', models.IntegerField(blank=True, null=True, verbose_name='question_8')),
                ('question_9', models.TextField(blank=True, null=True, verbose_name='question_9')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('exam_user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
