# Generated by Django 3.1.2 on 2022-03-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0002_auto_20220312_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.IntegerField(verbose_name='question_1')),
                ('question_2', models.IntegerField(verbose_name='question_2')),
                ('question_3', models.IntegerField(verbose_name='question_3')),
                ('question_4', models.IntegerField(verbose_name='question_4')),
                ('question_5', models.IntegerField(verbose_name='question_5')),
                ('question_6', models.IntegerField(verbose_name='question_6')),
                ('question_7', models.IntegerField(verbose_name='question_7')),
                ('question_8', models.IntegerField(verbose_name='question_8')),
                ('question_9', models.TextField(blank=True, null=True, verbose_name='question_9')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
            ],
        ),
    ]
