# Generated by Django 3.1.2 on 2022-03-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0004_exam_exam_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='question_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='question_1'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='question_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='question_2'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='question_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='question_3'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='question_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='question_4'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='question_5',
            field=models.IntegerField(blank=True, null=True, verbose_name='question_5'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='question_6',
            field=models.IntegerField(blank=True, null=True, verbose_name='question_6'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='question_7',
            field=models.IntegerField(blank=True, null=True, verbose_name='question_7'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='question_8',
            field=models.IntegerField(blank=True, null=True, verbose_name='question_8'),
        ),
    ]
