# Generated by Django 3.1.2 on 2022-03-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='final_score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='final score'),
        ),
    ]
