# Generated by Django 3.1.2 on 2022-03-12 10:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0003_auto_20220312_1350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Certificate',
        ),
    ]
